version: '3.4'

services:

  rabbitmq:
    container_name: 'rabbitmq'
    build:
      context: .
      dockerfile: rabbitmq.Dockerfile
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - rabbitmq_go_net

  publisher:
    image: ${DOCKER_REGISTRY-}publisher
    build:
      context: .
      dockerfile: Publisher/Dockerfile
    networks:
        - rabbitmq_go_net
    depends_on:
        - rabbitmq
    restart: on-failure

  subscriber:
    image: ${DOCKER_REGISTRY-}subscriber
    build:
      context: .
      dockerfile: Subscriber/Dockerfile
    networks:
        - rabbitmq_go_net
    depends_on:
        - rabbitmq
    restart: on-failure

networks:
  rabbitmq_go_net:
    driver: bridge

